version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - pandoc
  jobs:
    post_create_environment:
      - pip install torch==1.11.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu
      - pip install https://data.pyg.org/whl/torch-1.11.0%2Bcpu/torch_cluster-1.6.0-cp38-cp38-linux_x86_64.whl
      - pip install https://data.pyg.org/whl/torch-1.11.0%2Bcpu/torch_scatter-2.0.9-cp38-cp38-linux_x86_64.whl
      - pip install https://data.pyg.org/whl/torch-1.11.0%2Bcpu/torch_sparse-0.6.15-cp38-cp38-linux_x86_64.whl
      - pip install torch-geometric
      - pip install scSLAT==0.2.0
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: docs/requirements.txt